(ns mori
  (:require-macros
   [mori.macros :refer [mori-export property-export]])
  (:refer-clojure :exclude
   [count empty conj find nth assoc dissoc disj pop peek get
    empty? reverse into merge subvec keys vals
    equiv sort sort-by
    vector vec array-map hash-map set compare]))

(mori-export count cljs.core/count)
(mori-export empty cljs.core/empty)
(mori-export conj cljs.core/conj)
(mori-export find cljs.core/find)
(mori-export nth cljs.core/nth)
(mori-export assoc cljs.core/assoc)
(mori-export dissoc cljs.core/dissoc)
(mori-export disj cljs.core/disj)
(mori-export pop cljs.core/pop)
(mori-export peek cljs.core/peek)
(mori-export get cljs.core/get)
(mori-export isEmpty cljs.core/empty?)
(mori-export reverse cljs.core/reverse)
(mori-export into cljs.core/into)
(mori-export merge cljs.core/merge)
(mori-export subvec cljs.core/subvec)
(mori-export keys cljs.core/keys)
(mori-export vals cljs.core/vals)
(mori-export equiv cljs.core/==)
(mori-export sort cljs.core/sort)
(mori-export sortBy cljs.core/sort-by)
(mori-export vector cljs.core/vector)
(mori-export vec cljs.core/vec)
(mori-export Vector cljs.core/PersistentVector)
(property-export "Vector.prototype.nth" cljs.core/nth)
(property-export "Vector.prototype.peek" cljs.core/peek)
(property-export "Vector.prototype.pop" cljs.core/pop)
(property-export "Vector.prototype.conj" cljs.core/conj)
(property-export "Vector.prototype.equiv" cljs.core/==)
(property-export "Vector.prototype.empty" cljs.core/empty)
(property-export "Vector.prototype.count" cljs.core/count)
(property-export "Vector.prototype.lookup" cljs.core/lookup)
(property-export "Vector.prototype.key" cljs.core/key)
(property-export "Vector.prototype.val" cljs.core/val)
(property-export "Vector.prototype.assoc" cljs.core/assoc)
(property-export "Vector.prototype.assocN" cljs.core/assoc-n)
(property-export "Vector.prototype.reduce" cljs.core/reduce)
(property-export "Vector.prototype.kvReduce" cljs.core/kv-reduce)
(property-export "Vector.prototype.asTransient" cljs.core/as-transient)

(mori-export hashMap cljs.core/array-map)
(mori-export ArrayMap cljs.core/PersistentArrayMap)
(property-export "ArrayMap.prototype.keys" cljs.core/keys)
(property-export "ArrayMap.prototype.entries" cljs.core/entries)
(property-export "ArrayMap.prototype.values" cljs.core/values)
(property-export "ArrayMap.prototype.has" cljs.core/has)
(property-export "ArrayMap.prototype.get" cljs.core/get)
(property-export "ArrayMap.prototype.forEach" cljs.core/forEach)
(property-export "ArrayMap.prototype.conj" cljs.core/conj)
(property-export "ArrayMap.prototype.empty" cljs.core/empty)
(property-export "ArrayMap.prototype.equiv" cljs.core/==)
(property-export "ArrayMap.prototype.count" cljs.core/count)
(property-export "ArrayMap.prototype.lookup" cljs.core/lookup)
(property-export "ArrayMap.prototype.key" cljs.core/key)
(property-export "ArrayMap.prototype.val" cljs.core/val)
(property-export "ArrayMap.prototype.assoc" cljs.core/assoc)
(property-export "ArrayMap.prototype.contains" cljs.core/contains-key?)
(property-export "ArrayMap.prototype.dissoc" cljs.core/dissoc)
(property-export "ArrayMap.prototype.reduce" cljs.core/reduce)
(property-export "ArrayMap.prototype.kvReduce" cljs.core/kv-reduce)
(property-export "ArrayMap.prototype.asTransient" cljs.core/as-transient)

(defn ^:export arrayMapFromArray [arr no-clone no-check]
  (cljs.core/PersistentArrayMap.fromArray arr no-clone no-check))

(defn ^:export arrayMapUnwrap [m]
  (if (instance? cljs.core/PersistentArrayMap m)
    (.-arr m)
    (throw (js/Error. "Can only unwrap array maps"))))

(mori-export Map cljs.core/PersistentHashMap)
(property-export "Map.prototype.keys" cljs.core/keys)
(property-export "Map.prototype.entries" cljs.core/entries)
(property-export "Map.prototype.values" cljs.core/values)
(property-export "Map.prototype.has" cljs.core/has)
(property-export "Map.prototype.get" cljs.core/get)
(property-export "Map.prototype.forEach" cljs.core/forEach)
(property-export "Map.prototype.conj" cljs.core/conj)
(property-export "Map.prototype.empty" cljs.core/empty)
(property-export "Map.prototype.equiv" cljs.core/==)
(property-export "Map.prototype.count" cljs.core/count)
(property-export "Map.prototype.lookup" cljs.core/lookup)
(property-export "Map.prototype.key" cljs.core/key)
(property-export "Map.prototype.val" cljs.core/val)
(property-export "Map.prototype.assoc" cljs.core/assoc)
(property-export "Map.prototype.contains" cljs.core/contains-key?)
(property-export "Map.prototype.dissoc" cljs.core/dissoc)
(property-export "Map.prototype.reduce" cljs.core/reduce)
(property-export "Map.prototype.kvReduce" cljs.core/kv-reduce)
(property-export "Map.prototype.asTransient" cljs.core/as-transient)

(mori-export set cljs.core/set)
(mori-export Set cljs.core/PersistentHashSet)
(property-export "Set.prototype.get" cljs.core/get)
(property-export "Set.prototype.forEach" cljs.core/forEach)
(property-export "Set.prototype.conj" cljs.core/conj)
(property-export "Set.prototype.empty" cljs.core/empty)
(property-export "Set.prototype.equiv" cljs.core/==)
(property-export "Set.prototype.count" cljs.core/count)
(property-export "Set.prototype.lookup" cljs.core/lookup)
(property-export "Set.prototype.key" cljs.core/key)
(property-export "Set.prototype.val" cljs.core/val)
(property-export "Set.prototype.assoc" cljs.core/assoc)
(property-export "Set.prototype.contains" cljs.core/contains?)
(property-export "Set.prototype.disjoin" cljs.core/disjoin)

(mori-export compare cljs.core/compare)
